### ISSUE TITLE
User can turn their car.

### ISSUE THREAD

**Issue by alexdenbaugh** [alexdenbaugh/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] create data structure in JS
- [x] create turn function
- [x] create event listener for `keydown` events.
- [x] execute turn function based on `event.key`
- [x] make car turn smoothly with `transition `property
